config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'pages/info'
  mount Commontator::Engine => '/commontator'
  root to: redirect('/ideas')
  resources :ideas do
    member do
      put 'like', to: 'ideas#upvote'
      put 'dislike', to: 'ideas#downvote'
    end
  end

end

app/models/idea.rb
class Idea < ActiveRecord::Base
  mount_uploader :picture, PictureUploader
  belongs_to :user
  acts_as_commontable
  acts_as_votable

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :ideas
  acts_as_commontator
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :set_idea, only: [:show, :edit, :update, :destroy]

  # GET /ideas
  # GET /ideas.json
  def index
    @ideas = Idea.all
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
    commontator_thread_show(@idea)

  end

  # GET /ideas/new
  def new
    @idea = Idea.new
  end



  def upvote
  @idea = Idea.find(params[:id])
  @idea.upvote_by current_user
  redirect_to ideas_path
  end
  def downvote
  @idea = Idea.find(params[:id])
  @idea.downvote_by current_user
  redirect_to ideas_path
  end


  # GET /ideas/1/edit
  def edit
    @idea = current_user.ideas.find_by_id(params[:id])
    if @idea.nil?
    redirect_to ideas_path, flash: {alert: 'No existe la idea que desea modificar'}
    end
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = Idea.new(idea_params)
    @idea.user = current_user
    respond_to do |format|
      if @idea.save
        format.html { redirect_to @idea, notice: 'Idea was successfully created.' }
        format.json { render :show, status: :created, location: @idea }
      else
        format.html { render :new }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ideas/1
  # PATCH/PUT /ideas/1.json
  def update
    @idea = current_user.ideas.find(params[:id])
    respond_to do |format|
      if @idea.update(idea_params)
        format.html { redirect_to @idea, notice: 'Idea was successfully updated.' }
        format.json { render :show, status: :ok, location: @idea }
      else
        format.html { render :edit }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea.destroy
    respond_to do |format|
      format.html { redirect_to ideas_url, notice: 'Idea was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idea
      @idea = Idea.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def idea_params
      params.require(:idea).permit(:name, :description, :picture)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def info
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/ideas/_form.html.erb
<!-- <%= form_for(@idea) do |f| %>
  <% if @idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
      <% @idea.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.file_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %> -->
<div class="col-md-5">
  <%= form_for(@idea, html: {role: 'form'}) do |f| %>
    <% if @idea.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

        <ul>
        <% @idea.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control', placeholder: 'Nombre' %>
    </div>
    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_area :description, class: 'form-control', placeholder: 'Descripción' %>
    </div>
    <div class="form-group">
      <%= f.label :picture %>
      <%= f.file_field :picture %>
    </div>

    <%= f.submit class: 'btn btn-default' %>
    <%= link_to 'Back', ideas_path, class: 'btn btn-danger' %>
  <% end %>
</div>

app/views/ideas/edit.html.erb
<!-- <h1>Editing Idea</h1> -->
<h1>Edit - <%= @idea.name %></h1>
<%= render 'form' %>
<!--
<%= link_to 'Show', @idea %> |
<%= link_to 'Back', ideas_path %> -->

app/views/ideas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Ideas</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Picture</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ideas.each do |idea| %>
      <tr>
        <td><%= idea.name %></td>
        <td><%= idea.description %></td>
        <td><%= image_tag(idea.picture_url, :width => 100) %></td>

        <% if current_user.ideas.include? idea %>
        <td><%= link_to 'Edit', edit_idea_path(idea) %></td>
        <td><%= link_to 'Destroy', idea, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% else %>
        <td></td>
        <td></td>
        <% end %>
        <td><%= link_to 'Show', idea %></td>
        <td>Submitted <%= time_ago_in_words(idea.created_at) %></td>
        <td>
        <%= link_to like_idea_path(idea), method: :put do %>
          Upvote
          <%= idea.get_upvotes.size %>
        <% end %>
        </td>
        <td>
          <%= link_to dislike_idea_path(idea), method: :put do %>
            Downvote
            <%= idea.get_downvotes.size %>
          <% end %>
        </td>


        <!-- <td><%= link_to 'Edit', edit_idea_path(idea) %></td>
        <td><%= link_to 'Destroy', idea, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Idea', new_idea_path %>

<!-- <% @ideas.in_groups_of(3) do |group| %>
  <div class="row">
    <% group.compact.each do |idea| %>
      <div class="col-md-4">
        <%= image_tag idea.picture_url, class: 'img-thumbnail' if idea.picture.present?%>
        <h4><%= link_to idea.name, idea %></h4>
        <%= idea.description %>
      </div>
     <% end %>
  </div>
<% end %> -->

app/views/ideas/new.html.erb
<h1>New Idea</h1>

<%= render 'form' %>

<!-- <%= link_to 'Back', ideas_path %> -->

app/views/ideas/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<p>
  <strong>Name:</strong>
  <%= @idea.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @idea.description %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @idea.picture %>
  <p></p>
  <%= image_tag(@idea.picture_url, :width => 100) if @idea.picture.present? %>
</p>

<%= link_to 'Edit', edit_idea_path(@idea) %> |
<%= link_to 'Back', ideas_path %>
<%= commontator_thread(@idea) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Railsgirls</title>
  <link rel="stylesheet" href="//railsgirls.com/assets/bootstrap.css">
  <link rel="stylesheet" href="//railsgirls.com/assets/bootstrap-theme.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/ideas">The Idea app</a>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="active"><a href="/ideas">Ideas</a></li>
          <li class="active"><a href="/pages/info">About</a></li>
        </ul>
        <p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>

      </div>
    </div>
  </nav>

  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>

  <div class="container">
    <%= yield %>
  </div>
  <!-- <li class="<%= 'active' if current_page?(new_idea_path) %>">
    <%= link_to 'Nueva Idea', new_idea_path %>
  </li> -->

  <footer>
    <div class="container">
      Rails Girls 2015
    </div>
  </footer>
  <script src="//railsgirls.com/assets/bootstrap.js"></script>

</body>
</html>

app/views/pages/info.html.erb
<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
<div class="container">
	<div class="row">
		<div class="col-lg-3 col-sm-6">

            <div class="card hovercard">
                <div class="cardheader">

                </div>
                <div class="avatar">
                    <img alt="" src="https://media.licdn.com/media/p/1/000/0ca/263/3c75c17.jpg">
                </div>
                <div class="info">
                    <div class="title">
                        <a target="_blank" href="http://scripteden.com/">Script Eden</a>
                    </div>
                    <div class="desc">Passionate designer</div>
                    <div class="desc">Curious developer</div>
                    <div class="desc">Tech geek</div>
                </div>
                <div class="bottom">
                    <a class="btn btn-primary btn-twitter btn-sm" href="https://twitter.com/webmaniac">
                        <i class="fa fa-twitter"></i>
                    </a>
                    <a class="btn btn-danger btn-sm" rel="publisher"
                       href="https://plus.google.com/+ahmshahnuralam">
                        <i class="fa fa-google-plus"></i>
                    </a>
                    <a class="btn btn-primary btn-sm" rel="publisher"
                       href="https://plus.google.com/shahnuralam">
                        <i class="fa fa-facebook"></i>
                    </a>
                    <a class="btn btn-warning btn-sm" rel="publisher" href="https://plus.google.com/shahnuralam">
                        <i class="fa fa-behance"></i>
                    </a>
                </div>
            </div>

        </div>

	</div>
</div>